<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>False</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <WarningLevel>9999</WarningLevel>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn)</NoWarn>

    <!-- Pack everything with embedded .pdb -->
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup>
    <CompanyName>AuroraScienceHub</CompanyName>
    <CurrentYear>$([System.DateTime]::Now.ToString(yyyy))</CurrentYear>

    <Copyright>Copyright $(CurrentYear) © $(CompanyName). All rights reserved</Copyright>
    <Authors>$(CompanyName)</Authors>
    <Company>$(CompanyName)</Company>
    <Product>Aurora Science Hub Integrations</Product>
    <PackageProjectUrl>https://github.com/Aurora-Science-Hub/Integrations</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Aurora-Science-Hub/Integrations.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <PropertyGroup Label="Package Metadata">
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>https://github.com/Aurora-Science-Hub/Integrations/blob/main/RELEASE_NOTES.md</PackageReleaseNotes>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <PackageBaseVersion>10.0.0</PackageBaseVersion>
    <MinVerTagPrefix></MinVerTagPrefix>
  </PropertyGroup>

  <!--
    This instruction automatically allows XXX.Tests to access internals of XXX.
    Signed assemblies have to add friends manually because of public key requirement.
  -->
  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="AuroraScienceHub.Integrations.UnitTests" />
    <InternalsVisibleTo Include="AuroraScienceHub.Integrations.Benchmarks" />
  </ItemGroup>

  <!-- Automatically add dev packages to all projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
