<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AuroraScienceHub.Integrations.Benchmarks</AssemblyName>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- Disable entry point generation as this project has it's own entry point -->
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="NoaaClient\Ace\Samples\**" />
    <EmbeddedResource Include="NoaaClient\KpIndex\Samples\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NoaaClient\NoaaClient.csproj" />
  </ItemGroup>

</Project>
