<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>AuroraScienceHub.Integrations.Noaa</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AuroraScienceHub.Framework.Http" />
    <PackageReference Include="AuroraScienceHub.Framework.Utilities" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

</Project>
