<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>AuroraScienceHub.Integrations.UnitTests</AssemblyName>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Noaa\Noaa.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Noaa\Ace\Samples\**" />
    <EmbeddedResource Include="Noaa\Dscovr\Samples\**" />
    <EmbeddedResource Include="Noaa\KpIndex\Samples\**" />
  </ItemGroup>

</Project>
