<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <IsPackable>True</IsPackable>
  </PropertyGroup>

  <PropertyGroup Label="Package info">
    <Authors>Aleksei Ermilov;Alexander Nikolaev;Aurora Science Hub</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/Aurora-Science-Hub/Integrations</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Aurora-Science-Hub/Integrations.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageIcon>In_icon.png</PackageIcon>
    <Copyright>Copyright 2024-$([System.DateTime]::Now.ToString(yyyy)) Aurora Science Hub</Copyright>
    <DevelopmentDependency>false</DevelopmentDependency>
    <Language>en-US</Language>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\logo\In_icon.png" Pack="true" Visible="false" PackagePath="" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
